In [35]:
import torch
torch.manual_seed

rnncell = torch.nn.RNNCell(input_size=5, hidden_size=3)

b_hh = rnncell.bias_hh.detach().clone()
b_ih = rnncell.bias_ih.detach().clone()

w_hh = rnncell.weight_hh.detach().clone()
w_ih = rnncell.weight_ih.detach().clone()

x = torch.rand(5)
hx = torch.rand(3)
rnncell.forward(x, hx)

ih = torch.sum(w_ih * x, dim=1) + b_ih  
hh = torch.sum(w_hh * hx, dim=1) + b_hh

torch.tanh(ih+hh), rnncell.forward(x, hx)

weight_ih Parameter containing:
tensor([[ 0.4940,  0.2287, -0.4303,  0.3920,  0.1295],
        [ 0.1636, -0.5492, -0.1623, -0.2018, -0.5269],
        [-0.0669,  0.2648,  0.0019,  0.1291, -0.4242]], requires_grad=True)
weight_hh Parameter containing:
tensor([[ 0.1340,  0.3554, -0.0654],
        [-0.2137,  0.3757,  0.0877],
        [ 0.4380,  0.2446, -0.0223]], requires_grad=True)
bias_ih Parameter containing:
tensor([ 0.3585,  0.5241, -0.1306], requires_grad=True)
bias_hh Parameter containing:
tensor([-0.1206,  0.5283, -0.5432], requires_grad=True)


(tensor([ 0.4766,  0.4053, -0.5934]),
 tensor([ 0.4766,  0.4053, -0.5934], grad_fn=<SqueezeBackward1>))

In [43]:
import torch
torch.manual_seed

lstmcell = torch.nn.LSTMCell(input_size=5, hidden_size=3)

b_hh = lstmcell.bias_hh.detach().clone()
b_ih = lstmcell.bias_ih.detach().clone()

w_hh = lstmcell.weight_hh.detach().clone()
w_ih = lstmcell.weight_ih.detach().clone()


x = torch.rand(5)
hx = torch.rand(3)
cx = torch.rand(3)
lstmcell.forward(x, (hx, cx))

i = torch.sigmoid(torch.sum(w_ih * x, dim=1) + b_ih  + torch.sum(w_hh * hx, dim=1) + b_hh)

lstmcell.forward(x, (hx, cx))
i

tensor([0.3253, 0.4650, 0.4628, 0.6643, 0.2161, 0.6512, 0.5377, 0.8213, 0.6058,
        0.6678, 0.1814, 0.4305])